// pokemon-data.js
// Dados da LuaHMoonMC

export const TYPE = {
  Normal:   { pt:"Normal",   c:"#A8A77A" },
  Fire:     { pt:"Fogo",     c:"#EE8130" },
  Water:    { pt:"Água",     c:"#6390F0" },
  Electric: { pt:"Elétrico", c:"#F7D02C" },
  Grass:    { pt:"Planta",   c:"#7AC74C" },
  Ice:      { pt:"Gelo",     c:"#96D9D6" },
  Fighting: { pt:"Lutador",  c:"#C22E28" },
  Poison:   { pt:"Venenoso", c:"#A33EA1" },
  Ground:   { pt:"Terra",    c:"#E2BF65" },
  Flying:   { pt:"Voador",   c:"#A98FF3" },
  Psychic:  { pt:"Psíquico", c:"#F95587" },
  Bug:      { pt:"Inseto",    c:"#A6B91A" },
  Rock:     { pt:"Pedra",     c:"#B6A136" },
  Ghost:    { pt:"Fantasma",  c:"#735797" },
  Dragon:   { pt:"Dragão",    c:"#6F35FC" },
  Dark:     { pt:"Sombrio",   c:"#705746" },
  Steel:    { pt:"Aço",       c:"#B7B7CE" },
  Fairy:    { pt:"Fada",      c:"#D685AD" }
};

export const TYPE_ORDER = [
  "All","Normal","Fire","Water","Electric","Grass","Ice","Fighting","Poison","Ground",
  "Flying","Psychic","Bug","Rock","Ghost","Dragon","Dark","Steel","Fairy"
];

export const RAW = [
  { name:"pumpkaboo", iv:91, types:["Ghost","Grass"], favorite:true },
  { name:"arbok", iv:93, types:["Poison"], favorite:true },
  { name:"krabby", iv:75, types:["Water"], favorite:true, dynamax:true },
  { name:"wobbuffet", iv:95, types:["Psychic"] },
  { name:"omanyte", iv:77, types:["Rock","Water"], dynamax:true },
  { name:"cetitan", iv:100, types:["Ice"] },
  { name:"cetoddle", iv:97, types:["Ice"] },
  { name:"yungoos", iv:91, types:["Normal"] },
  { name:"indeedee", iv:93, types:["Psychic","Normal"] },
  { name:"nidorina", iv:100, types:["Poison"] },
  { name:"leafeon", iv:93, types:["Grass"], favorite:true },
  { name:"sandslash-alola", iv:91, types:["Ice","Steel"] },
  { name:"parasect", iv:93, types:["Bug","Grass"] },
  { name:"exeggutor", iv:91, types:["Grass","Psychic"] },
  { name:"hariyama", iv:91, types:["Fighting"] },
  { name:"magcargo", iv:91, types:["Fire","Rock"] },
  { name:"medicham", iv:97, types:["Fighting","Psychic"] },
  { name:"scizor", iv:91, types:["Bug","Steel"] },
  { name:"doublade", iv:75, types:["Steel","Ghost"] },
  { name:"kadabra", iv:86, types:["Psychic"], dynamax:true },
  { name:"jigglypuff", iv:91, types:["Normal","Fairy"], xmas:true },
  { name:"blastoise", iv:91, types:["Water"], xmas:true },
  { name:"alakazam", iv:95, types:["Psychic"], favorite:true },
  { name:"persian", iv:91, types:["Normal"], favorite:true },
  { name:"sentret", iv:93, types:["Normal"] },
  { name:"swampert", iv:86, types:["Water","Ground"] },
  { name:"sliggoo", iv:91, types:["Dragon"] },
  { name:"charizard", iv:86, types:["Fire","Flying"] },
  { name:"krabby", iv:80, types:["Water"], favorite:true },
  { name:"sealeo", iv:82, types:["Ice","Water"], dynamax:true },
  { name:"wartortle", iv:93, types:["Water"], xmas:true },
  { name:"haunter", iv:95, types:["Ghost","Poison"] },
  { name:"shelmet", iv:91, types:["Bug"] },
  { name:"throh", iv:91, types:["Fighting"] },
  { name:"wigglytuff", iv:100, types:["Normal","Fairy"] },
  { name:"beedrill", iv:93, types:["Bug","Poison"], favorite:true },
  { name:"charmeleon", iv:95, types:["Fire"] },
  { name:"swalot", iv:95, types:["Poison"] },
  { name:"gulpin", iv:97, types:["Poison"] },
  { name:"gardevoir", iv:95, types:["Psychic","Fairy"] },
  { name:"dugtrio", iv:93, types:["Ground"] },
  { name:"skarmory", iv:95, types:["Steel","Flying"] },
  { name:"mismagius", iv:95, types:["Ghost"], favorite:true },
  { name:"vaporeon", iv:91, types:["Water"], favorite:true },
  { name:"stufful", iv:100, types:["Normal","Fighting"] },
  { name:"munna", iv:91, types:["Psychic"] },
  { name:"ralts", iv:85, types:["Psychic","Fairy"], dynamax:true },
  { name:"noctowl", iv:97, types:["Normal","Flying"] },
  { name:"xatu", iv:97, types:["Psychic","Flying"] },
  { name:"baltoy", iv:14, types:["Ground","Psychic"] },
  { name:"flareon", iv:93, types:["Fire"], favorite:true },
  { name:"venomoth", iv:93, types:["Bug","Poison"] },
  { name:"ampharos", iv:97, types:["Electric"] },
  { name:"whirlipede", iv:95, types:["Bug","Poison"] },
  { name:"butterfree", iv:93, types:["Bug","Flying"], favorite:true },
  { name:"electrode", iv:97, types:["Electric"] },
  { name:"pelipper", iv:97, types:["Water","Flying"] },
  { name:"espeon", iv:93, types:["Psychic"], favorite:true, dynamax:true },
  { name:"koffing", iv:95, types:["Poison"] },
  { name:"skitty", iv:93, types:["Normal"], favorite:true },
  { name:"gengar", iv:97, types:["Ghost","Poison"] },
  { name:"heracross", iv:93, types:["Bug","Fighting"], shiny:true },
  { name:"golduck", iv:93, types:["Water"], favorite:true },
  { name:"hypno", iv:95, types:["Psychic"], favorite:true },
  { name:"gothorita", iv:95, types:["Psychic"] },
  { name:"machamp", iv:100, types:["Fighting"], favorite:true },
  { name:"weepinbell", iv:93, types:["Grass","Poison"] },
  { name:"magnezone", iv:100, types:["Electric","Steel"] },
  { name:"swellow", iv:97, types:["Normal","Flying"] },
  { name:"lapras", iv:93, types:["Water","Ice"], favorite:true },
  { name:"toxel", iv:91, types:["Electric","Poison"] },
  { name:"pancham", iv:93, types:["Fighting"] },
  { name:"lapras", iv:82, types:["Water","Ice"], favorite:true },
  { name:"avalugg", iv:95, types:["Ice"] },
  { name:"spoink", iv:91, types:["Psychic"], favorite:true },
  { name:"dusclops", iv:91, types:["Ghost"] },
  { name:"jynx", iv:93, types:["Ice","Psychic"], favorite:true },
  { name:"wooper", iv:93, types:["Water","Ground"] },
  { name:"umbreon", iv:91, types:["Dark"], favorite:true },
  { name:"mightyena", iv:93, types:["Dark"] },
  { name:"rapidash", iv:91, types:["Fire"], favorite:true },
  { name:"metapod", iv:95, types:["Bug"] },
  { name:"minun", iv:97, types:["Electric"] },
  { name:"lunatone", iv:93, types:["Rock","Psychic"], favorite:true },
  { name:"drifblim", iv:97, types:["Ghost","Flying"] },
  { name:"hitmonchan", iv:95, types:["Fighting"], favorite:true },
  { name:"ledian", iv:100, types:["Bug","Flying"] },
  { name:"mienfoo", iv:93, types:["Fighting"] },
  { name:"azumarill", iv:91, types:["Water","Fairy"] },
  { name:"arcanine", iv:91, types:["Fire"] },
  { name:"gastly", iv:93, types:["Ghost","Poison"] },
  { name:"vanillish", iv:93, types:["Ice"] },
  { name:"snorlax", iv:95, types:["Normal"] },
  { name:"voltorb", iv:93, types:["Electric"] },
  { name:"vileplume", iv:93, types:["Grass","Poison"] },
  { name:"poliwag", iv:93, types:["Water"] },
  { name:"electabuzz", iv:95, types:["Electric"] },
  { name:"gyarados", iv:100, types:["Water","Flying"], favorite:true },
  { name:"probopass", iv:91, types:["Rock","Steel"] },
  { name:"zygarde-10", iv:82, types:["Dragon","Ground"] },
  { name:"misdreavus", iv:91, types:["Ghost"], favorite:true },
  { name:"lunatone", iv:91, types:["Rock","Psychic"], favorite:true },
  { name:"sandshrew", iv:93, types:["Ground"] },
  { name:"jolteon", iv:95, types:["Electric"], favorite:true },
  { name:"onix", iv:95, types:["Rock","Ground"] },
  { name:"eevee", iv:84, types:["Normal"], dynamax:true },
  { name:"meganium", iv:95, types:["Grass"], favorite:true },
  { name:"gyarados", iv:62, types:["Water","Flying"], favorite:true },
  { name:"starmie", iv:60, types:["Water","Psychic"], favorite:true },
  { name:"leafeon", iv:84, types:["Grass"], favorite:true },
  { name:"hitmonlee", iv:91, types:["Fighting"] },
  { name:"lunatone", iv:91, types:["Rock","Psychic"], favorite:true },
  { name:"crawdaunt", iv:91, types:["Water","Dark"] },
  { name:"vibrava", iv:97, types:["Ground","Dragon"] },
  { name:"dolliv", iv:93, types:["Grass","Normal"] },
  { name:"simipour", iv:94, types:["Water"] },
  { name:"corphish", iv:97, types:["Water"], favorite:true },
  { name:"dratini", iv:95, types:["Dragon"], favorite:true },
  { name:"tentacruel", iv:95, types:["Water","Poison"] },
  { name:"dustox", iv:95, types:["Bug","Poison"] },
  { name:"staryu", iv:100, types:["Water"], favorite:true },
  { name:"lombre", iv:93, types:["Water","Grass"], favorite:true },
  { name:"pansear", iv:91, types:["Fire"] },
  { name:"hitmontop", iv:97, types:["Fighting"] },
  { name:"numel", iv:93, types:["Fire","Ground"] },
  { name:"girafarig", iv:93, types:["Normal","Psychic"] },
  { name:"seel", iv:95, types:["Water"] },
  { name:"ponyta", iv:35, types:["Fire"], favorite:true, shiny:true },
  { name:"castform-rainy", iv:97, types:["Water"], favorite:true },
  { name:"eevee", iv:0, types:["Normal"] },
  { name:"pansage", iv:91, types:["Grass"] },
  { name:"ditto", iv:64, types:["Normal"], favorite:true, shiny:true },
  { name:"beautifly", iv:91, types:["Bug","Flying"], favorite:true },
  { name:"meditite", iv:93, types:["Fighting","Psychic"] },
  { name:"wurmple", iv:93, types:["Bug"] },
  { name:"jigglypuff", iv:91, types:["Normal","Fairy"] },
  { name:"mrmime", iv:100, types:["Psychic","Fairy"], favorite:true },
  { name:"lapras", iv:80, types:["Water","Ice"], favorite:true },
  { name:"sharpedo", iv:100, types:["Water","Dark"] },
  { name:"lucario", iv:100, types:["Fighting","Steel"], favorite:true },
  { name:"krabby", iv:82, types:["Water"], favorite:true, dynamax:true },
  { name:"meditite", iv:97, types:["Fighting","Psychic"] },
  { name:"absol", iv:91, types:["Dark"] },
  { name:"luxio", iv:100, types:["Electric"], favorite:true },
  { name:"pawmo", iv:93, types:["Electric","Fighting"] },
  { name:"sylveon", iv:100, types:["Fairy"] },
  { name:"sceptile", iv:100, types:["Grass"], favorite:true },
  { name:"tauros", iv:100, types:["Normal"], favorite:true },
  { name:"pumpkaboo", iv:100, types:["Ghost","Grass"], favorite:true },
  { name:"infernape", iv:95, types:["Fire","Fighting"], favorite:true },
  { name:"combusken", iv:100, types:["Fire","Fighting"] },
  { name:"duskull", iv:91, types:["Ghost"], shiny:true },
  { name:"clefable", iv:100, types:["Fairy"] },
  { name:"shaymin-sky", iv:71, types:["Grass","Flying"] },
  { name:"rapidash", iv:100, types:["Fire"], favorite:true },
  { name:"raichu", iv:100, types:["Electric"], favorite:true },
  { name:"seaking", iv:100, types:["Water"], favorite:true },
  { name:"swablu", iv:95, types:["Normal","Flying"] },
  { name:"solrock", iv:100, types:["Rock","Psychic"], favorite:true },
  { name:"goldeen", iv:97, types:["Water"] },
  { name:"magmar", iv:100, types:["Fire"] },
  { name:"piloswine", iv:100, types:["Ice","Ground"] },
  { name:"bellossom", iv:100, types:["Grass"] },
  { name:"koffing", iv:100, types:["Poison"] },
  { name:"electabuzz", iv:100, types:["Electric"] },
  { name:"hitmonchan", iv:100, types:["Fighting"], favorite:true },
  { name:"porygon2", iv:100, types:["Normal"] },
  { name:"azumarill", iv:91, types:["Water","Fairy"] },
  { name:"marshtomp", iv:91, types:["Water","Ground"] },
  { name:"poochyena", iv:91, types:["Dark"], favorite:true },
  { name:"snorlax", iv:97, types:["Normal"] },
  { name:"exploud", iv:95, types:["Normal"] },
  { name:"meloetta", iv:77, types:["Normal","Psychic"] },
  { name:"zangoose", iv:91, types:["Normal"] },
  { name:"cranidos", iv:91, types:["Rock"] },
  { name:"sableye", iv:100, types:["Dark","Ghost"] },
  { name:"torterra", iv:100, types:["Grass","Ground"] },
  { name:"diancie", iv:86, types:["Rock","Fairy"] },
  { name:"dusknoir", iv:100, types:["Ghost"], favorite:true },
  { name:"dialga", iv:80, types:["Steel","Dragon"] },
  { name:"butterfree", iv:100, types:["Bug","Flying"], favorite:true },
  { name:"shiftry", iv:100, types:["Grass","Dark"] },
  { name:"boltund", iv:93, types:["Electric"] },
  { name:"cacnea", iv:93, types:["Grass"] },
  { name:"heatmor", iv:100, types:["Fire"] },
  { name:"roselia", iv:100, types:["Grass","Poison"], favorite:true },
  { name:"dugtrio", iv:97, types:["Ground"] },
  { name:"golem", iv:100, types:["Rock","Ground"] },
  { name:"ivysaur", iv:100, types:["Grass","Poison"], favorite:true },
  { name:"tangela", iv:100, types:["Grass"], favorite:true },
  { name:"pinsir", iv:100, types:["Bug"] },
  { name:"mesprit", iv:68, types:["Psychic"], favorite:true },
  { name:"azelf", iv:71, types:["Psychic"], favorite:true },
  { name:"uxie", iv:53, types:["Psychic"], favorite:true },
  { name:"zapdos", iv:80, types:["Electric","Flying"], favorite:true },
  { name:"regigigas", iv:88, types:["Normal"], favorite:true },
  { name:"altaria", iv:95, types:["Dragon","Flying"] },
  { name:"tornadus", iv:82, types:["Flying"] },
  { name:"luvdisc", iv:97, types:["Water"], favorite:true },
  { name:"delcatty", iv:97, types:["Normal"] },
  { name:"croconaw", iv:86, types:["Water"], shiny:true },
  { name:"espeon", iv:95, types:["Psychic"], favorite:true },
  { name:"quaxly", iv:86, types:["Water"] },
  { name:"spinda", iv:93, types:["Normal"] },
  { name:"jolteon", iv:97, types:["Electric"], favorite:true },
  { name:"nidorino", iv:100, types:["Poison"] },
  { name:"zapdos", iv:75, types:["Electric","Flying"], favorite:true },
  { name:"horsea", iv:95, types:["Water"], favorite:true },
  { name:"torkoal", iv:100, types:["Fire"], favorite:true },
  { name:"mrmime-galar", iv:84, types:["Ice","Psychic"] },
  { name:"dragonair", iv:100, types:["Dragon"], favorite:true },
  { name:"geodude", iv:93, types:["Rock","Ground"] },
  { name:"blissey", iv:100, types:["Normal"] },
  { name:"palkia-origin", iv:77, types:["Water","Dragon"], shiny:true },
  { name:"floette", iv:93, types:["Fairy"] },
  { name:"palkia-origin", iv:73, types:["Water","Dragon"], shiny:true },
  { name:"dialga-origin", iv:80, types:["Steel","Dragon"] },
  { name:"palkia-origin", iv:83, types:["Water","Dragon"] },
  { name:"dragonite", iv:100, types:["Dragon","Flying"] },
  { name:"empoleon", iv:100, types:["Water","Steel"], favorite:true },
  { name:"spritzee", iv:100, types:["Fairy"] },
  { name:"venusaur", iv:100, types:["Grass","Poison"], favorite:true },
  { name:"lapras", iv:88, types:["Water","Ice"], favorite:true },
  { name:"lunala", iv:84, types:["Psychic","Ghost"], favorite:true },
  { name:"articuno", iv:80, types:["Ice","Flying"], favorite:true },
  { name:"moltres", iv:91, types:["Fire","Flying"], favorite:true },
  { name:"abra", iv:93, types:["Psychic"] },
  { name:"charmander", iv:91, types:["Fire"] },
  { name:"bellossom", iv:91, types:["Grass"] },
  { name:"poliwrath", iv:100, types:["Water","Fighting"], favorite:true },
  { name:"sandslash", iv:91, types:["Ground"] },
  { name:"deoxys", iv:71, types:["Psychic"], favorite:true },
  { name:"poliwhirl", iv:84, types:["Water"], favorite:true, shiny:true },
  { name:"darkrai", iv:82, types:["Dark"], favorite:true },
  { name:"arbok", iv:95, types:["Poison"], favorite:true },
  { name:"slowking", iv:93, types:["Water","Psychic"] },
  { name:"raticate", iv:91, types:["Normal"] },
  { name:"crobat", iv:95, types:["Poison","Flying"] },
  { name:"zacian", iv:93, types:["Fairy"], shiny:true },
  { name:"shuckle", iv:93, types:["Bug","Rock"] },
  { name:"snorlax", iv:93, types:["Normal"] },
  { name:"quilava", iv:95, types:["Fire"] },
  { name:"zamazenta", iv:84, types:["Fighting"] },
  { name:"huntail", iv:86, types:["Water"], shiny:true },
  { name:"aggron", iv:100, types:["Steel","Rock"] },
  { name:"chinchou", iv:53, types:["Water","Electric"], shiny:true },
  { name:"kyogre", iv:91, types:["Water"] },
  { name:"kyogre", iv:84, types:["Water"] },
  { name:"bulbasaur", iv:93, types:["Grass","Poison"] },
  { name:"castform-sunny", iv:68, types:["Fire"], shiny:true },
  { name:"groudon", iv:84, types:["Ground"] },
  { name:"solrock", iv:100, types:["Rock","Psychic"], favorite:true },
  { name:"ribombee", iv:100, types:["Bug","Fairy"] },
  { name:"nuzleaf", iv:95, types:["Grass","Dark"] },
  { name:"castform-sunny", iv:100, types:["Fire"] },
  { name:"clefairy", iv:93, types:["Fairy"] },
  { name:"snover", iv:93, types:["Grass","Ice"] },
  { name:"castform-rainy", iv:93, types:["Water"], favorite:true },
  { name:"castform", iv:95, types:["Normal"] },
  { name:"hatenna", iv:97, types:["Psychic"], dynamax:true },
  { name:"squirtle", iv:93, types:["Water"] },
  { name:"castform-rainy", iv:62, types:["Water"], favorite:true, shiny:true },
  { name:"groudon", iv:91, types:["Ground"] },
  { name:"groudon", iv:93, types:["Ground"] },
  { name:"braixen", iv:95, types:["Fire"] },
  { name:"marshadow", iv:80, types:["Fighting","Ghost"] },
  { name:"rillaboom", iv:100, types:["Grass"] },
  { name:"skeledirge", iv:100, types:["Fire","Ghost"] },
  { name:"starmie", iv:88, types:["Water","Psychic"], favorite:true },
  { name:"wartortle", iv:91, types:["Water"] },
  { name:"sneasel-hisui", iv:100, types:["Fighting","Poison"] },
  { name:"tandemaus", iv:95, types:["Normal"] },
  { name:"cinderace", iv:91, types:["Fire"] },
  { name:"victreebel", iv:100, types:["Grass","Poison"] },
  { name:"teddiursa", iv:100, types:["Normal"] },
  { name:"dartrix", iv:91, types:["Grass","Flying"] },
  { name:"arcanine-hisui", iv:100, types:["Fire","Rock"] },
  { name:"slowpoke", iv:100, types:["Water","Psychic"] },
  { name:"espeon", iv:88, types:["Psychic"], favorite:true },
  { name:"starmie", iv:73, types:["Water","Psychic"], favorite:true },
  { name:"lunatone", iv:91, types:["Rock","Psychic"], favorite:true },
  { name:"jynx", iv:100, types:["Ice","Psychic"], favorite:true },
  { name:"seadra", iv:100, types:["Water"] },
  { name:"blaziken", iv:100, types:["Fire","Fighting"] },
  { name:"flamigo", iv:100, types:["Flying","Fighting"] },
  { name:"umbreon", iv:84, types:["Dark"], favorite:true },
  { name:"espeon", iv:62, types:["Psychic"], favorite:true },
  { name:"starmie", iv:75, types:["Water","Psychic"], favorite:true },
  { name:"flareon", iv:55, types:["Fire"], favorite:true },
  { name:"zacian", iv:75, types:["Fairy"] },
  { name:"zacian", iv:80, types:["Fairy"] },
  { name:"mewtwo", iv:80, types:["Psychic"], favorite:true },
  { name:"mewtwo", iv:82, types:["Psychic"], favorite:true },
  { name:"mewtwo", iv:91, types:["Psychic"], favorite:true },
  { name:"chansey", iv:82, types:["Normal"], dynamax:true },
  { name:"regirock", iv:77, types:["Rock"] },
  { name:"charmander", iv:95, types:["Fire"] },
  { name:"igglybuff", iv:95, types:["Normal","Fairy"] },
  { name:"deoxys-speed", iv:93, types:["Psychic"], favorite:true },
  { name:"scorbunny", iv:91, types:["Fire"], dynamax:true },
  { name:"drapion", iv:93, types:["Poison","Dark"] },
  { name:"varoom", iv:91, types:["Steel","Poison"] },
  { name:"pawmi", iv:95, types:["Electric"] },
  { name:"rayquaza", iv:84, types:["Dragon","Flying"] },
  { name:"hooh", iv:84, types:["Fire","Flying"] },
  { name:"lugia", iv:82, types:["Psychic","Flying"] },
  { name:"giratina", iv:86, types:["Ghost","Dragon"] },
  { name:"houndoom", iv:93, types:["Dark","Fire"] },
  { name:"blastoise", iv:95, types:["Water"] },
  { name:"palkia", iv:86, types:["Water","Dragon"] },
  { name:"articuno", iv:88, types:["Ice","Flying"], favorite:true },
  { name:"eevee", iv:91, types:["Normal"] },
  { name:"moltres", iv:73, types:["Fire","Flying"], favorite:true },
  { name:"honedge", iv:84, types:["Steel","Ghost"] },
  { name:"hakamo-o", iv:91, types:["Dragon","Fighting"] },
  { name:"kyogre", iv:84, types:["Water"] },
  { name:"farfetchd", iv:100, types:["Normal","Flying"] },
  { name:"swirlix", iv:97, types:["Fairy"] },
  { name:"dottler", iv:91, types:["Bug","Psychic"] },
  { name:"porygon", iv:100, types:["Normal"] },
  { name:"marowak", iv:91, types:["Ground"] },
  { name:"kyogre", iv:91, types:["Water"] },
  { name:"dragonair", iv:91, types:["Dragon"], favorite:true },
  { name:"togetic", iv:91, types:["Fairy","Flying"] },
  { name:"zangoose", iv:93, types:["Normal"] },
  { name:"blissey", iv:10, types:["Normal"] },
  { name:"ninetales", iv:100, types:["Fire"] },
  { name:"larvitar", iv:91, types:["Rock","Ground"] },
  { name:"bouffalant", iv:91, types:["Normal"] },
  { name:"palkia", iv:82, types:["Water","Dragon"] },
  { name:"lumineon", iv:100, types:["Water"] },
  { name:"mienshao", iv:100, types:["Fighting"] },
  { name:"donphan", iv:100, types:["Ground"] },
  { name:"chimecho", iv:100, types:["Psychic"] },
  { name:"gimmighoul", iv:88, types:["Ghost"] },
  { name:"espeon", iv:95, types:["Psychic"], favorite:true },
  { name:"necrozma", iv:84, types:["Psychic"] },
  { name:"xurkitree", iv:88, types:["Electric"] },
  { name:"aerodactyl", iv:82, types:["Rock","Flying"] },
  { name:"deoxys-defense", iv:82, types:["Psychic"], favorite:true },
  { name:"nihilego", iv:84, types:["Rock","Poison"] },
  { name:"latios", iv:73, types:["Dragon","Psychic"] },
  { name:"cloyster", iv:82, types:["Water","Ice"] },
  { name:"misdreavus", iv:100, types:["Ghost"], favorite:true },
  { name:"solgaleo", iv:88, types:["Psychic","Steel"] },
  { name:"relicanth", iv:100, types:["Water","Rock"] },
  { name:"medicham", iv:100, types:["Fighting","Psychic"] },
  { name:"pidgeot", iv:100, types:["Normal","Flying"] },
  { name:"starmie", iv:86, types:["Water","Psychic"], favorite:true },
  { name:"solgaleo", iv:77, types:["Psychic","Steel"] },
  { name:"vigoroth", iv:100, types:["Normal"] },
  { name:"kyurem", iv:80, types:["Dragon","Ice"] },
  { name:"perrserker", iv:93, types:["Steel"] },
  { name:"jolteon", iv:100, types:["Electric"], favorite:true },
  { name:"garchomp", iv:100, types:["Dragon","Ground"] },
  { name:"whimsicott", iv:93, types:["Grass","Fairy"] },
  { name:"miltank", iv:100, types:["Normal"] },
  { name:"charizard", iv:100, types:["Fire","Flying"] },
  { name:"meowscarada", iv:100, types:["Grass","Dark"] },
  { name:"morgrem", iv:93, types:["Dark","Fairy"] },
  { name:"palkia", iv:88, types:["Water","Dragon"] },
  { name:"sawsbuck", iv:100, types:["Normal","Grass"] },
  { name:"hooh", iv:82, types:["Fire","Flying"] },
  { name:"dubwool", iv:97, types:["Normal"] },
  { name:"gyarados", iv:91, types:["Water","Flying"], favorite:true },
  { name:"impidimp", iv:97, types:["Dark","Fairy"] },
  { name:"linoone", iv:100, types:["Normal"] },
  { name:"pelipper", iv:91, types:["Water","Flying"] },
  { name:"trumbeak", iv:91, types:["Normal","Flying"] },
  { name:"yamask", iv:91, types:["Ghost"] },
  { name:"venonat", iv:97, types:["Bug","Poison"] },
  { name:"umbreon", iv:93, types:["Dark"], favorite:true },
  { name:"grimer", iv:100, types:["Poison"] },
  { name:"magneton", iv:91, types:["Electric","Steel"] },
  { name:"shiinotic", iv:95, types:["Grass","Fairy"] },
  { name:"marowak", iv:93, types:["Ground"] },
  { name:"mew", iv:77, types:["Psychic"], favorite:true },
  { name:"prinplup", iv:91, types:["Water"] },
  { name:"swinub", iv:91, types:["Ice","Ground"] },
  { name:"ponyta", iv:93, types:["Fire"], favorite:true },
  { name:"stufful", iv:95, types:["Normal","Fighting"] },
  { name:"beheeyem", iv:95, types:["Psychic"] },
  { name:"pyroar", iv:93, types:["Fire","Normal"] },
  { name:"kabuto", iv:91, types:["Rock","Water"] },
  { name:"azelf", iv:82, types:["Psychic"], favorite:true, shiny:true },
  { name:"growlithe", iv:66, types:["Fire"], shiny:true },
  { name:"giratina", iv:100, types:["Ghost","Dragon"] },
  { name:"manectric", iv:91, types:["Electric"] },
  { name:"nidoqueen", iv:100, types:["Poison","Ground"] },
  { name:"maushold", iv:91, types:["Normal"] },
  { name:"glalie", iv:100, types:["Ice"] },
  { name:"yanma", iv:100, types:["Bug","Flying"] },
  { name:"vulpix", iv:100, types:["Fire"] },
  { name:"stunfisk", iv:100, types:["Ground","Electric"] },
  { name:"aipom", iv:100, types:["Normal"] },
  { name:"celebi", iv:86, types:["Psychic","Grass"] },
  { name:"abomasnow", iv:94, types:["Grass","Ice"] },
  { name:"mesprit", iv:86, types:["Psychic"], favorite:true },
  { name:"milotic", iv:91, types:["Water"] },
  { name:"sneasel", iv:88, types:["Dark","Ice"] },
  { name:"carvanha", iv:91, types:["Water","Dark"] },
  { name:"barboach", iv:95, types:["Water","Ground"] },
  { name:"drowzee", iv:95, types:["Psychic"] },
  { name:"drowzee", iv:100, types:["Psychic"] },
  { name:"frogadier", iv:95, types:["Water"] },
  { name:"lampent", iv:91, types:["Ghost","Fire"] },
  { name:"monferno", iv:91, types:["Fire","Fighting"] },
  { name:"cursola", iv:88, types:["Ghost"], shiny:true },
  { name:"stunfisk-galar", iv:93, types:["Ground","Steel"] },
  { name:"uxie", iv:100, types:["Psychic"], favorite:true },
  { name:"raticate-alola", iv:100, types:["Dark","Normal"] },
  { name:"dodrio", iv:95, types:["Normal","Flying"] },
  { name:"lucario", iv:100, types:["Fighting","Steel"], favorite:true },
  { name:"gothitelle", iv:100, types:["Psychic"] },
  { name:"excadrill", iv:100, types:["Ground","Steel"] },
  { name:"venomoth", iv:24, types:["Bug","Poison"], shiny:true },
  { name:"jynx", iv:93, types:["Ice","Psychic"], favorite:true },
  { name:"crustle", iv:100, types:["Bug","Rock"] },
  { name:"masquerain", iv:100, types:["Bug","Flying"] },
  { name:"seadra", iv:84, types:["Water"] },
];

const HOURS_LEADING_SINCE = new Date(2025, 11, 28, 12, 0, 0); // 28/12/2025 12:00

export const GYM_STATS = {
  gymsDefeated: 2058,
  get hoursLeading(){
    const ms = Date.now() - HOURS_LEADING_SINCE.getTime();
    return Math.max(0, Math.floor(ms / 36e5));
  }
};

export const META = {
  lastUpdated: "2026-08-12"
};
